### ISSUE TITLE
www.oolite.space not working

### ISSUE THREAD

**Issue by AnotherCommander** [OoliteProject/oolite-web#6]
The url www.oolite.space leads to this:
![error](https://imgur.com/IQ1y7mP.png)

oolite.space without the www. at the start works as expected. 

This has been happening since the change of the main website from the old server to the new one. The issue has been confirmed on Edge, Chrome and Firefox browsers.

**Comment by HiranChaudhuri** [comment]
I added a DNS record on CloudFlare. It shows impact as the DNS name is now found - the desired result is not yet visible.

![Screenshot from 2023-08-29 09-21-28](https://github.com/OoliteProject/oolite-web/assets/6866487/81a8d470-b078-4c7c-967e-d78bbabc7f44)

**Comment by HiranChaudhuri** [comment]
Under Workers & Pages / oolite-web I added a custom domain.

![Screenshot from 2023-08-29 09-53-16](https://github.com/OoliteProject/oolite-web/assets/6866487/d093486a-3742-48f7-a554-c0515c2af9e8)

Now these URLs show good results:
```
http://www.oolite.space
https://www.oolite.space

```

**Comment by AnotherCommander** [comment]
Looking good, many thanks. Closing issue.
